### ISSUE TITLE
using with angular_cli

### ISSUE THREAD

**Issue by Benjamin-FC** [krsween/seek-final#1]
Excellent demo and starter repo!
Is it possible to get the seek_starter and then use the angular_cli to add the rest of the code?

Thank you!!
-Jenny

**Comment by krsween** [comment]
Hey, @jennyraj —

Thanks for the compliment! At the time that I wrote this, the CLI didn't have [ES6 support](https://github.com/angular/angular-cli#known-issues) and it still doesn't. Once the CLI supports ES6, I could shift the direction of this repo to leverage that. I'm also looking at all of the changes required to migrate this (and the video series) to support RC. So I'll be making some updates over the next few weeks for that, and I'll roadmap this for when the CLI gets updated.

Thanks!
K.

**Comment by Benjamin-FC** [comment]
Awesome! Thank you so much!
